import "reflect-metadata";
import {z} from "zod";

export interface ToolParameter {
  name: string;
  type: string;
  description: string;
  required: boolean;
  default: unknown;
}

export interface OpenAISchemaProperty {
  type: string;
  description: string;
  items?: {type: string};
}

export interface OpenAIFunctionSchema {
  type: "function";
  function: {
    name: string;
    description: string;
    parameters: {
      type: "object";
      properties: Record<string, OpenAISchemaProperty>;
      required: string[];
    };
  };
}

export type ToolActionMethod = (...args: any[]) => string | Promise<string>;

export interface FunctionTool<
  TArgs extends Record<string, any> = Record<string, any>,
> {
  name: string;
  description: string;
  /**
   * 可选：对 JSON arguments 进行结构和类型校验。
   */
  schema?: z.ZodType<TArgs>;
  /**
   * 函数工具执行体：接收强类型参数。
   */
  func: (args: TArgs) => string | Promise<string>;
}

/**
 * 定义函数工具：
 * - 若提供 schema，则 func 参数类型会被约束为与 schema 一致。
 * - 若未提供 schema，则按传入的泛型/推断类型工作。
 */
export function defineFunctionTool<TArgs extends Record<string, any>>(
  tool: FunctionTool<TArgs>,
): FunctionTool<TArgs> {
  return tool;
}

type ToolActionMeta = {
  name?: string;
  description?: string;
};

const TOOL_ACTION_META_KEY = Symbol("tool_action_meta");

/**
 * 装饰器：标记一个方法为可展开的工具 action
 */
export function toolAction(
  name?: string,
  description?: string,
): MethodDecorator {
  return (_target, _propertyKey, descriptor) => {
    const fn = descriptor.value;
    if (typeof fn !== "function") {
      throw new Error("@toolAction 只能用于方法");
    }
    Reflect.defineMetadata(
      TOOL_ACTION_META_KEY,
      {name, description} satisfies ToolActionMeta,
      fn,
    );
  };
}

export abstract class Tool {
  public readonly name: string;
  public readonly description: string;
  public readonly expandable: boolean;
  private runtimeSchemaCache: z.ZodObject<z.ZodRawShape> | null = null;

  constructor(name: string, description: string, expandable = false) {
    this.name = name;
    this.description = description;
    this.expandable = expandable;
  }

  abstract run(parameters: Record<string, unknown>): string | Promise<string>;

  abstract getParameters(): ToolParameter[];

  /**
   * 获取展开后的子工具列表
   * 默认从标记了 @toolAction 的方法自动生成
   */
  getExpandedTools(): Tool[] | null {
    if (!this.expandable) {
      return null;
    }

    const prototype = Object.getPrototypeOf(this) as object;
    const methodNames = Object.getOwnPropertyNames(prototype).filter(
      (methodName) => {
        if (methodName === "constructor") return false;
        const candidate = (this as Record<string, unknown>)[methodName];
        return typeof candidate === "function";
      },
    );

    const tools: Tool[] = [];
    for (const methodName of methodNames) {
      const method = (this as Record<string, unknown>)[methodName];
      if (typeof method !== "function") continue;

      const meta = Reflect.getMetadata(TOOL_ACTION_META_KEY, method) as
        | ToolActionMeta
        | undefined;
      if (!meta) continue;

      tools.push(
        new AutoGeneratedTool(
          this,
          methodName,
          method as ToolActionMethod,
          meta.name,
          meta.description,
        ),
      );
    }

    return tools.length ? tools : null;
  }

  validateParameters(parameters: Record<string, unknown>): boolean {
    return this.validateAndNormalizeParameters(parameters).success;
  }

  validateAndNormalizeParameters(
    parameters: Record<string, unknown>,
  ):
    | {success: true; data: Record<string, unknown>}
    | {success: false; error: string} {
    const schema = this.getRuntimeSchema();
    const parsed = schema.safeParse(parameters);
    if (!parsed.success) {
      const details = parsed.error.issues
        .map((issue) => `${issue.path.join(".") || "input"}: ${issue.message}`)
        .join("; ");
      return {success: false, error: details};
    }

    return {success: true, data: parsed.data as Record<string, unknown>};
  }

  toDict(): {
    name: string;
    description: string;
    parameters: ToolParameter[];
  } {
    return {
      name: this.name,
      description: this.description,
      parameters: this.getParameters(),
    };
  }

  private getRuntimeSchema(): z.ZodObject<z.ZodRawShape> {
    if (this.runtimeSchemaCache) {
      return this.runtimeSchemaCache;
    }

    const shape: Record<string, z.ZodType<unknown>> = {};
    for (const param of this.getParameters()) {
      let base: z.ZodType<unknown>;
      switch (param.type) {
        case "number":
          base = z.coerce.number();
          break;
        case "boolean":
          base = z.coerce.boolean();
          break;
        case "array":
          base = z.array(z.unknown());
          break;
        case "object":
          base = z.record(z.string(), z.unknown());
          break;
        case "string":
        default:
          base = z.string();
          break;
      }

      const withDefault =
        param.default !== null && param.default !== undefined
          ? base.default(param.default as never)
          : base;
      shape[param.name] = param.required ? withDefault : withDefault.optional();
    }

    this.runtimeSchemaCache = z.object(shape).strict();
    return this.runtimeSchemaCache;
  }

  toOpenAISchema(): OpenAIFunctionSchema {
    const parameters = this.getParameters();
    const properties: Record<string, OpenAISchemaProperty> = {};
    const required: string[] = [];

    for (const param of parameters) {
      const prop: OpenAISchemaProperty = {
        type: param.type,
        description:
          param.default !== null && param.default !== undefined
            ? `${param.description} (默认: ${String(param.default)})`
            : param.description,
      };

      if (param.type === "array") {
        prop.items = {type: "string"};
      }

      properties[param.name] = prop;
      if (param.required) {
        required.push(param.name);
      }
    }

    return {
      type: "function",
      function: {
        name: this.name,
        description: this.description,
        parameters: {
          type: "object",
          properties,
          required,
        },
      },
    };
  }

  toString(): string {
    return `Tool(name=${this.name})`;
  }
}

export class AutoGeneratedTool extends Tool {
  private readonly parent: Tool;
  private readonly methodName: string;
  private readonly method: ToolActionMethod;
  private readonly parameters: ToolParameter[];

  constructor(
    parent: Tool,
    methodName: string,
    method: ToolActionMethod,
    name?: string,
    description?: string,
  ) {
    const generatedName =
      name ?? `${parent.name}_${methodName.replace(/^_+/, "")}`;
    const generatedDescription =
      description ??
      AutoGeneratedTool.extractDescriptionFromFunction(methodName, method);

    super(generatedName, generatedDescription, false);
    this.parent = parent;
    this.methodName = methodName;
    this.method = method;
    this.parameters = this.parseParameters();
  }

  private static extractDescriptionFromFunction(
    methodName: string,
    method: Function,
  ): string {
    const source = method.toString();
    const blockCommentMatch = source.match(/\/\*\*([\s\S]*?)\*\//);
    if (blockCommentMatch) {
      const lines = blockCommentMatch[1]
        .split("\n")
        .map((l) => l.replace(/^\s*\*\s?/, "").trim())
        .filter(Boolean)
        .filter((l) => !l.startsWith("@param") && !l.startsWith("@returns"));
      if (lines.length > 0) return lines[0]!;
    }
    return `执行 ${methodName}`;
  }

  private parseParameters(): ToolParameter[] {
    const rawArgs = this.getParameterNamesFromFunction(this.method);
    const declaredTypes =
      (Reflect.getMetadata(
        "design:paramtypes",
        this.parent,
        this.methodName,
      ) as Array<new (...args: any[]) => unknown> | undefined) ?? [];

    return rawArgs.map((arg, index) => {
      const {name, hasDefault, defaultValueRaw} = this.parseArgToken(arg);
      const mappedType = this.jsTypeToToolType(declaredTypes[index]);
      const defaultValue = hasDefault
        ? this.tryParseLiteral(defaultValueRaw)
        : null;
      return {
        name,
        type: mappedType,
        description: `参数 ${name}`,
        required: !hasDefault,
        default: defaultValue,
      };
    });
  }

  private getParameterNamesFromFunction(fn: Function): string[] {
    const src = fn
      .toString()
      .replace(/\/\*[\s\S]*?\*\//g, "")
      .replace(/\/\/.*$/gm, "");
    const match =
      src.match(/^[^(]*\(([^)]*)\)/) ??
      src.match(/^(?:async\s*)?([^=\s]+)\s*=>/);
    if (!match) return [];

    const raw = (match[1] ?? "").trim();
    if (!raw) return [];

    return raw
      .split(",")
      .map((s) => s.trim())
      .filter((s) => s.length > 0)
      .filter((s) => !s.startsWith("..."));
  }

  private parseArgToken(token: string): {
    name: string;
    hasDefault: boolean;
    defaultValueRaw: string;
  } {
    const equalIndex = token.indexOf("=");
    if (equalIndex < 0) {
      return {
        name: token.replace(/\?/g, "").trim(),
        hasDefault: false,
        defaultValueRaw: "",
      };
    }
    const name = token.slice(0, equalIndex).replace(/\?/g, "").trim();
    const defaultValueRaw = token.slice(equalIndex + 1).trim();
    return {name, hasDefault: true, defaultValueRaw};
  }

  private tryParseLiteral(raw: string): unknown {
    if (raw === "undefined") return undefined;
    if (raw === "null") return null;
    if (raw === "true") return true;
    if (raw === "false") return false;
    if (/^[-+]?\d+(?:\.\d+)?$/.test(raw)) return Number(raw);
    if (
      (raw.startsWith('"') && raw.endsWith('"')) ||
      (raw.startsWith("'") && raw.endsWith("'"))
    ) {
      return raw.slice(1, -1);
    }
    return raw;
  }

  private jsTypeToToolType(jsType?: new (...args: any[]) => unknown): string {
    switch (jsType) {
      case String:
        return "string";
      case Number:
        return "number";
      case Boolean:
        return "boolean";
      case Array:
        return "array";
      case Object:
        return "object";
      default:
        return "string";
    }
  }

  getParameters(): ToolParameter[] {
    return this.parameters;
  }

  async run(parameters: Record<string, unknown>): Promise<string> {
    const orderedArgs = this.parameters.map(
      (p) => parameters[p.name] ?? p.default,
    );
    const result = await this.method.apply(this.parent, orderedArgs);
    return String(result);
  }
}

